import{W,H,table,palette}from'./config.js?v=20260828-2';
import{bumpers,posts,targets,lanes,walls,flipperSpecs,inserts}from'./layout.js?v=20260828-2';
import{clamp,circleHit,segmentHit,rectHit,flipperHit,integrate}from'./physics.js?v=20260828-2';
import{Roulette}from'./roulette.js?v=20260828-2';
import{LightingController}from'./lighting.js?v=20260828-2';
import{GameUI}from'./ui.js?v=20260828-2';
import{AudioFX}from'./audio.js?v=20260828-2';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),ui=new GameUI,audio=new AudioFX,lighting=new LightingController;
const safeStorage={get(key){try{return localStorage.getItem(key)}catch{return null}},set(key,value){try{localStorage.setItem(key,value)}catch{}}};
const state={running:false,score:0,high:+safeStorage.get('neonRouletteHigh')||0,balls:3,multiplier:1,targetHits:new Set,bumperBank:new Set,lanes:new Set,combo:0,comboTime:0,lastHit:'',ballSave:0,frenzy:0,magnet:0,shake:0,flash:0,plunger:0,launching:false,particles:[],pop:[],time:0,metrics:{bumperHits:0,targetHits:0,laneHits:0,rouletteSpins:0,flipperHits:0,drains:0}};
const flippers=Object.fromEntries(Object.entries(flipperSpecs).map(([side,spec])=>[side,{...spec,angle:spec.rest,angularVelocity:0,pressed:false,hitCool:0}]));
let balls=[],last=performance.now(),acc=0;
const roulette=new Roulette(awardReward,reward=>{ui.setLcd(reward.label,`${state.targetHits.size}/3 BANK`,reward.color);audio.tick()});

function inputLog(type,data={}){console.info('[pinball-input]',type,JSON.stringify({at:Math.round(performance.now()),...data}))}
function capBallSpeed(ball){const speed=Math.hypot(ball.vx,ball.vy);if(speed>table.maxSpeed){ball.vx*=table.maxSpeed/speed;ball.vy*=table.maxSpeed/speed}}
function newBall(){balls=[{x:748,y:1010,vx:0,vy:0,r:table.ballRadius,trail:[],launched:false,shotGate:false,saveUsed:false,stuck:0,lastX:0,lastY:0,kickbacks:{left:true,right:true}}];state.plunger=0;state.launching=false;ui.setLcd('HOLD TO LAUNCH','短押し:右500  •  長押し:左500');inputLog('ball-ready',{ballsRemaining:state.balls})}
function reset(){state.score=0;state.balls=3;state.multiplier=1;state.targetHits.clear();state.bumperBank.clear();state.lanes.clear();state.combo=0;state.comboTime=0;state.lastHit='';state.ballSave=8;state.frenzy=0;state.magnet=0;state.running=true;state.pop=[];state.particles=[];state.metrics={bumperHits:0,targetHits:0,laneHits:0,rouletteSpins:0,flipperHits:0,drains:0};lighting.reset();newBall();sync()}
function sync(){state.high=Math.max(state.high,state.score);ui.sync(state);ui.lighting(lighting)}
function addScore(value,label,x=400,y=540){const n=value*state.multiplier;state.score+=n;state.pop.push({x,y,text:`+${n}`,life:1});if(label)ui.message(label);sync()}
function particles(x,y,color,n=10,speed=240){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=50+Math.random()*speed;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:.4+Math.random()*.55})}}
function registerHit(kind,id,x,y,base){if(state.lastHit!==kind+id&&state.comboTime>0)state.combo++;else if(state.comboTime<=0)state.combo=1;state.lastHit=kind+id;state.comboTime=3.15;lighting.hitCombo(state.combo);addScore(base+Math.max(0,state.combo-1)*120,state.combo>=4?`${state.combo} HIT COMBO!`:null,x,y);if(state.combo===6){state.multiplier=Math.min(5,state.multiplier+1);lighting.setMultiplier(state.multiplier);ui.message(`COMBO ×${state.multiplier}`)} }
function triggerRoulette(source='targets'){if(!roulette.spin())return;state.metrics.rouletteSpins++;lighting.startRoulette();ui.spin(true);ui.setLcd('SPINNING...',source==='bumpers'?'500 BANK COMPLETE':'A • B • C COMPLETE',palette.pink);ui.message('NEON ROULETTE!');state.targetHits.clear();state.bumperBank.clear();lighting.clearTargetBank();inputLog('roulette-start',{source,spins:state.metrics.rouletteSpins})}
function awardReward(reward){ui.spin(false);ui.setLcd(reward.label,'HIT A • B • C TO RE-SPIN',reward.color);lighting.award();audio.award();ui.message(reward.label);switch(reward.id){case'JACKPOT':addScore(30000);break;case'MULTI':state.multiplier=Math.min(5,state.multiplier+1);lighting.setMultiplier(state.multiplier);break;case'FRENZY':state.frenzy=18;break;case'SAVE':state.ballSave=Math.max(state.ballSave,22);break;case'BONUS':state.balls=Math.min(5,state.balls+1);break;case'MAGNET':state.magnet=15;break}sync();inputLog('roulette-award',{reward:reward.id,multiplier:state.multiplier,balls:state.balls})}

function press(which,on){const f=flippers[which];if(on&&!f.pressed){audio.flip();navigator.vibrate?.(12)}f.pressed=on;ui.control(which,on);if(which==='right'&&balls[0]&&!balls[0].launched){if(on){state.launching=true;inputLog('plunger-down',{charge:+state.plunger.toFixed(3)})}else if(state.launching)launch()}}
function launch(){const b=balls[0];if(!b||b.launched)return;const charge=state.plunger,speed=1580+charge*470;b.launched=true;b.launchCharge=charge;b.vy=-speed;b.vx=0;state.launching=false;state.ballSave=b.saveUsed?0:8;inputLog('launch',{charge:+charge.toFixed(3),speed:Math.round(speed),saveAvailable:!b.saveUsed,x:b.x,y:b.y});audio.tone(90,.16,'sawtooth',.08,260);ui.setLcd('BALL IN PLAY',charge>.62?'POWER SHOT → LEFT 500':'SKILL SHOT → RIGHT 500')}
function controls(){const activePointers=new Map,releasePointer=id=>{const name=activePointers.get(id);if(!name)return;activePointers.delete(id);if(![...activePointers.values()].includes(name))press(name,false);inputLog('pointer-up',{id,name})},releaseAll=()=>{for(const id of[...activePointers.keys()])releasePointer(id)},bind=(name,el)=>{el.addEventListener('pointerdown',event=>{event.preventDefault();if(activePointers.has(event.pointerId))return;activePointers.set(event.pointerId,name);press(name,true);inputLog('pointer-down',{id:event.pointerId,name,type:event.pointerType});try{el.setPointerCapture?.(event.pointerId)}catch(error){inputLog('capture-unavailable',{name,error:error?.name||'unknown'})}});el.addEventListener('pointerup',event=>releasePointer(event.pointerId));el.addEventListener('pointercancel',event=>releasePointer(event.pointerId));el.addEventListener('lostpointercapture',event=>releasePointer(event.pointerId));if(!window.PointerEvent){el.addEventListener('touchstart',event=>{event.preventDefault();for(const touch of event.changedTouches){const id=`touch-${touch.identifier}`;activePointers.set(id,name);press(name,true);inputLog('touch-down',{id,name})}},{passive:false});for(const type of['touchend','touchcancel'])el.addEventListener(type,event=>{event.preventDefault();for(const touch of event.changedTouches)releasePointer(`touch-${touch.identifier}`)},{passive:false})}};bind('left',ui.left);bind('right',ui.right);addEventListener('pointerup',event=>releasePointer(event.pointerId));addEventListener('pointercancel',event=>releasePointer(event.pointerId));addEventListener('blur',releaseAll);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseAll()});addEventListener('keydown',event=>{if(['ArrowLeft','KeyZ'].includes(event.code))press('left',true);if(['ArrowRight','KeyX','Space'].includes(event.code))press('right',true)});addEventListener('keyup',event=>{if(['ArrowLeft','KeyZ'].includes(event.code))press('left',false);if(['ArrowRight','KeyX','Space'].includes(event.code))press('right',false)});ui.start.onclick=()=>{ui.startGame();reset();inputLog('game-start');try{audio.init()}catch(error){inputLog('audio-unavailable',{error:error?.name||'unknown'})}};canvas.addEventListener('pointerdown',event=>{event.preventDefault();const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const x=(event.clientX-r.left)/r.width*canvas.width,y=(event.clientY-r.top)/r.height*canvas.height;if(y<=820)return;const name=x<canvas.width/2?'left':'right';activePointers.set(event.pointerId,name);press(name,true);inputLog('canvas-down',{id:event.pointerId,name,type:event.pointerType,x:Math.round(x),y:Math.round(y)});try{canvas.setPointerCapture?.(event.pointerId)}catch(error){inputLog('capture-unavailable',{name,error:error?.name||'unknown'})}});canvas.addEventListener('pointerup',event=>releasePointer(event.pointerId));canvas.addEventListener('pointercancel',event=>releasePointer(event.pointerId))}
function updateFlipper(f,dt){const target=f.pressed?f.active:f.rest,d=target-f.angle,velocity=clamp(d*44,-25,25);f.angularVelocity=velocity;f.angle+=velocity*dt;if(Math.abs(d)<.012){f.angle=target;f.angularVelocity=0}}

function step(dt){state.time+=dt;roulette.update(dt);lighting.update(dt);ui.lighting(lighting);updateFlipper(flippers.left,dt);updateFlipper(flippers.right,dt);if(state.launching)state.plunger=clamp(state.plunger+dt*.75,0,1);if(state.comboTime>0){state.comboTime-=dt;if(state.comboTime<=0)state.combo=0}state.ballSave=Math.max(0,state.ballSave-dt);state.frenzy=Math.max(0,state.frenzy-dt);state.magnet=Math.max(0,state.magnet-dt);state.shake=Math.max(0,state.shake-dt);state.flash=Math.max(0,state.flash-dt);
 for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=300*dt;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);for(const p of state.pop){p.y-=40*dt;p.life-=dt}state.pop=state.pop.filter(p=>p.life>0);
 for(const b of balls){if(!b.launched)continue;b.lastX=b.x;b.lastY=b.y;integrate(b,dt);
  if(!b.shotGate&&b.x>720&&b.y<224&&b.vy<0){const aim=b.launchCharge||0;b.x=690;b.y=112;b.vx=-400-aim*270;b.vy=95-aim*145;b.shotGate=true;inputLog('shooter-exit',{x:b.x,y:b.y,vx:Math.round(b.vx),vy:Math.round(b.vy),aim:+aim.toFixed(3)});particles(724,190,palette.cyan,14);ui.message(aim>.62?'POWER SKILL SHOT!':'SKILL SHOT!')}
  if(b.shotGate&&b.x>725&&b.y>850){b.x=704;b.vx=-Math.max(430,Math.abs(b.vx))}
  if(state.magnet>0&&b.y<560){const dx=400-b.x,dy=345-b.y,d=Math.hypot(dx,dy);if(d<350){b.vx+=dx/d*210*dt;b.vy+=dy/d*210*dt}}
  for(let k=0;k<2;k++){for(const [a,z]of walls)segmentHit(b,a,z,.65);for(const p of posts)if(circleHit(b,p.x,p.y,p.r,.8,28))particles(p.x,p.y,palette.cyan,3)}
  for(const [side,f]of Object.entries(flippers)){if(flipperHit(b,f)&&!f.hitCool){capBallSpeed(b);f.hitCool=.12;state.metrics.flipperHits++;inputLog('flipper-hit',{side,pressed:f.pressed,x:Math.round(b.x),y:Math.round(b.y),vx:Math.round(b.vx),vy:Math.round(b.vy),hits:state.metrics.flipperHits})}}
  for(const f of Object.values(flippers))f.hitCool=Math.max(0,f.hitCool-dt);
  for(const q of bumpers){if(circleHit(b,q.x,q.y,q.r,.84,state.frenzy>0?540:410)){if(!q.cool){q.cool=.085;b.vy-=105;b.vx+=(400-q.x)*.16;state.metrics.bumperHits++;state.bumperBank.add(q.id);lighting.hitBumper(q.id);registerHit('bumper',q.id,q.x,q.y,state.frenzy>0?q.score*3:q.score);audio.bumper();particles(q.x,q.y,q.color,17,310);state.shake=.11;navigator.vibrate?.(8);inputLog('bumper-hit',{id:q.id,bank:state.bumperBank.size,combo:state.combo,total:state.metrics.bumperHits});if(state.bumperBank.size===3)triggerRoulette('bumpers')}}q.cool=Math.max(0,(q.cool||0)-dt)}
  for(const target of targets){if(rectHit(b,target)&&!target.cool){target.cool=.3;b.vy=Math.min(b.vy,-470);b.vx+=(400-target.x)*.26;state.targetHits.add(target.id);state.metrics.targetHits++;lighting.hitTarget(target.id);registerHit('target',target.id,target.x,target.y,1100);audio.target();particles(target.x,target.y,target.color,14,280);inputLog('target-hit',{id:target.id,bank:state.targetHits.size,total:state.metrics.targetHits});if(state.targetHits.size===3)triggerRoulette('targets')}target.cool=Math.max(0,(target.cool||0)-dt)}
  if((b.lastY>174&&b.y<=174)||(b.lastY<174&&b.y>=174)){for(const lane of lanes)if(Math.abs(b.x-lane.x)<64&&!state.lanes.has(lane.id)){state.lanes.add(lane.id);state.metrics.laneHits++;lighting.hitLane(lane.id);registerHit('lane',lane.id,lane.x,155,1300);particles(lane.x,150,palette.amber,10);inputLog('lane-hit',{id:lane.id,bank:state.lanes.size,total:state.metrics.laneHits});if(state.lanes.size===3){state.lanes.clear();lighting.clearLanes();state.multiplier=Math.min(5,state.multiplier+1);lighting.setMultiplier(state.multiplier);addScore(6000,`LANES ×${state.multiplier}`)}}}
  if(b.shotGate&&b.y>930&&b.x<94&&b.kickbacks.left){b.kickbacks.left=false;b.x=192;b.y=872;b.vx=520;b.vy=-900;lighting.add(.04);particles(92,950,palette.green,18,300);ui.message('LEFT KICKBACK!');inputLog('kickback',{side:'left',x:Math.round(b.x),y:Math.round(b.y)})}
  if(b.shotGate&&b.y>930&&b.x>706&&b.kickbacks.right){b.kickbacks.right=false;b.x=608;b.y=872;b.vx=-520;b.vy=-900;lighting.add(.04);particles(708,950,palette.green,18,300);ui.message('RIGHT KICKBACK!');inputLog('kickback',{side:'right',x:Math.round(b.x),y:Math.round(b.y)})}
  capBallSpeed(b);const move=Math.hypot(b.x-b.lastX,b.y-b.lastY);b.stuck=move<.05?b.stuck+dt:0;if(b.stuck>2.1&&b.y<1060){b.vx+=(Math.random()-.5)*320;b.vy-=250;b.stuck=0;ui.message('BALL SEARCH')}
  if(b.y>table.drainY)drain(b)
 }
}

function drain(ball){if(!balls.includes(ball))return;if(state.ballSave>0&&!ball.saveUsed){Object.assign(ball,{x:748,y:1010,vx:0,vy:0,launched:false,shotGate:false,saveUsed:true,stuck:0,lastX:748,lastY:1010});state.launching=false;state.plunger=0;state.ballSave=0;ui.setLcd('BALL SAVED','右下を押して再発射',palette.green);ui.message('BALL SAVED!');inputLog('ball-saved-ready');audio.award();return}balls.splice(balls.indexOf(ball),1);state.balls--;state.metrics.drains++;inputLog('drain',{ballsRemaining:state.balls,drains:state.metrics.drains,metrics:state.metrics});audio.drain();sync();if(state.balls>0){ui.message('SHOOT AGAIN');setTimeout(()=>state.running&&newBall(),850)}else gameOver()}
function gameOver(){state.running=false;safeStorage.set('neonRouletteHigh',Math.floor(state.high));ui.gameOver(state.score);inputLog('game-over',{score:Math.floor(state.score),metrics:state.metrics})}

function rgba(hex,alpha){const n=parseInt(hex.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${alpha})`}
function strokePath(points){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))ctx.lineTo(p.x,p.y)}
function drawRail(points,accent='',lit=0){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';strokePath(points.map(p=>({x:p.x+7,y:p.y+10})));ctx.strokeStyle='rgba(0,0,0,.72)';ctx.lineWidth=23;ctx.stroke();strokePath(points);const metal=ctx.createLinearGradient(points[0].x,points[0].y,points.at(-1).x,points.at(-1).y);metal.addColorStop(0,'#252d38');metal.addColorStop(.3,'#eef5ff');metal.addColorStop(.55,'#718093');metal.addColorStop(.78,'#f8fbff');metal.addColorStop(1,'#303946');ctx.strokeStyle=metal;ctx.lineWidth=15;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.82)';ctx.lineWidth=3;ctx.stroke();if(accent&&lit>0){ctx.shadowColor=accent;ctx.shadowBlur=12+lit*25;ctx.globalAlpha=.35+lit*.65;ctx.strokeStyle=accent;ctx.lineWidth=4+lit*3;ctx.stroke()}ctx.restore()}
function drawTube(points,color,intensity,width=5){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';strokePath(points);ctx.globalAlpha=.14+.28*intensity;ctx.shadowColor=color;ctx.shadowBlur=30+intensity*34;ctx.strokeStyle=color;ctx.lineWidth=width+12;ctx.stroke();strokePath(points);ctx.globalAlpha=.38+.62*intensity;ctx.shadowBlur=12+intensity*25;ctx.strokeStyle=color;ctx.lineWidth=width+3;ctx.stroke();strokePath(points);ctx.globalAlpha=.62+.38*intensity;ctx.shadowBlur=3;ctx.strokeStyle='#f4fdff';ctx.lineWidth=Math.max(1.5,width*.28);ctx.stroke();ctx.restore()}
function drawBackground(light){const ambient=.12+light.energy*.32;const g=ctx.createRadialGradient(400,180,40,400,680,760);g.addColorStop(0,`rgba(41,65,110,${.42+ambient})`);g.addColorStop(.35,`rgba(12,34,66,${.75+ambient*.2})`);g.addColorStop(.78,'#080b19');g.addColorStop(1,'#02040a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const side=ctx.createLinearGradient(0,0,W,0);side.addColorStop(0,'rgba(0,0,0,.86)');side.addColorStop(.1,'rgba(0,0,0,.12)');side.addColorStop(.88,'rgba(0,0,0,.06)');side.addColorStop(1,'rgba(0,0,0,.88)');ctx.fillStyle=side;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.055+light.energy*.08;ctx.strokeStyle=palette.cyan;ctx.lineWidth=1.5;for(let y=-120;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y+190);ctx.stroke()}ctx.restore();const halo=ctx.createRadialGradient(400,390,30,400,390,330);halo.addColorStop(0,`rgba(255,67,167,${light.roulette*.24+light.reward*.12})`);halo.addColorStop(1,'transparent');ctx.fillStyle=halo;ctx.fillRect(80,70,640,650)}
function drawLane(lane){const lit=lighting.laneLit(lane.id),power=lit?1:.08+lighting.energy*.2;ctx.save();ctx.fillStyle=lit?rgba(palette.amber,.2):'rgba(10,14,28,.78)';ctx.fillRect(lane.x-51,82,102,94);ctx.shadowColor=palette.amber;ctx.shadowBlur=lit?28:0;ctx.strokeStyle=lit?palette.amber:'#364054';ctx.lineWidth=lit?6:4;ctx.strokeRect(lane.x-51,82,102,94);ctx.shadowBlur=0;ctx.fillStyle=lit?'#fff':'#758097';ctx.font='800 24px "Courier New"';ctx.textAlign='center';ctx.fillText(lane.id,lane.x,141);if(power>.35)drawTube([{x:lane.x-38,y:166},{x:lane.x+38,y:166}],palette.amber,power,3);ctx.restore()}
function drawLCD(light){ctx.save();ctx.fillStyle='rgba(0,0,0,.82)';ctx.shadowColor='#000';ctx.shadowBlur=24;ctx.fillRect(246,442,308,142);ctx.shadowBlur=0;const power=.25+light.energy*.45+light.roulette*.7+light.reward*.5;drawTube([{x:246,y:442},{x:554,y:442},{x:554,y:584},{x:246,y:584},{x:246,y:442}],palette.pink,clamp(power,0,1),5);ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(258,454,284,22);ctx.restore()}
function drawBumper(q){const active=lighting.bumperLit(q.id)||q.cool>0,power=active?clamp(.7+(q.cool?1:lighting.energy*.3),0,1):.08+lighting.energy*.12;ctx.save();ctx.beginPath();ctx.ellipse(q.x+8,q.y+15,q.r+15,q.r*.95,0,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,.72)';ctx.fill();const metal=ctx.createRadialGradient(q.x-21,q.y-23,3,q.x,q.y,q.r+13);metal.addColorStop(0,'#fff');metal.addColorStop(.11,'#aeb9c8');metal.addColorStop(.34,active?q.color:'#3d4654');metal.addColorStop(.72,'#18202d');metal.addColorStop(1,'#05070c');ctx.beginPath();ctx.arc(q.x,q.y,q.r+12,0,Math.PI*2);ctx.fillStyle=metal;ctx.fill();ctx.shadowColor=q.color;ctx.shadowBlur=power*42;ctx.globalAlpha=.28+power*.72;ctx.strokeStyle=q.color;ctx.lineWidth=5+power*5;ctx.stroke();ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.beginPath();ctx.arc(q.x,q.y,q.r-16,0,Math.PI*2);ctx.fillStyle=active?rgba(q.color,.9):'#111724';ctx.fill();ctx.strokeStyle=active?'#fff':'#4b5667';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=active?'#fff':'#8b95a7';ctx.font='900 22px "Courier New"';ctx.textAlign='center';ctx.fillText('500',q.x,q.y+7);ctx.fillStyle=active?q.color:'#586172';ctx.font='700 11px sans-serif';ctx.fillText(q.id,q.x,q.y+37);ctx.restore()}
function drawTarget(target){const lit=lighting.targetLit(target.id),power=lit?1:.08+lighting.energy*.15;ctx.save();ctx.translate(target.x,target.y);ctx.rotate(target.angle);ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(-target.w/2+5,-target.h/2+8,target.w,target.h);const tg=ctx.createLinearGradient(0,-target.h/2,0,target.h/2);tg.addColorStop(0,'#f5fbff');tg.addColorStop(.2,lit?target.color:'#697383');tg.addColorStop(.52,lit?'#fff':'#202838');tg.addColorStop(1,lit?rgba(target.color,.65):'#0b0e15');ctx.fillStyle=tg;ctx.shadowColor=target.color;ctx.shadowBlur=power*28;ctx.fillRect(-target.w/2,-target.h/2,target.w,target.h);ctx.shadowBlur=0;ctx.strokeStyle=lit?'#fff':'#475267';ctx.lineWidth=2;ctx.strokeRect(-target.w/2,-target.h/2,target.w,target.h);ctx.fillStyle=lit?'#080b12':'#b1bac8';ctx.font='900 16px sans-serif';ctx.textAlign='center';ctx.fillText(target.id,0,6);ctx.restore()}
function drawPost(post){ctx.save();ctx.beginPath();ctx.arc(post.x+5,post.y+7,post.r+3,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,.7)';ctx.fill();const pg=ctx.createRadialGradient(post.x-6,post.y-8,2,post.x,post.y,post.r);pg.addColorStop(0,'#fff');pg.addColorStop(.3,'#cbd7e4');pg.addColorStop(.65,'#657184');pg.addColorStop(1,'#202734');ctx.beginPath();ctx.arc(post.x,post.y,post.r,0,Math.PI*2);ctx.fillStyle=pg;ctx.fill();ctx.strokeStyle='#e9f6ff';ctx.globalAlpha=.65;ctx.lineWidth=2;ctx.stroke();ctx.restore()}
function drawInsert(insert,light){const on=light.stage>=insert.stage,power=on ? .72+light.pulse*.28 : .06;ctx.save();ctx.beginPath();ctx.moveTo(insert.x,insert.y-10);ctx.lineTo(insert.x+9,insert.y+8);ctx.lineTo(insert.x-9,insert.y+8);ctx.closePath();ctx.fillStyle=on?rgba(insert.color,.82):'#151b29';ctx.shadowColor=insert.color;ctx.shadowBlur=on?18+light.pulse*20:0;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=on?'#fff':'#3e4859';ctx.lineWidth=2;ctx.stroke();ctx.restore();if(on&&light.pulse>.45)drawTube([{x:insert.x-11,y:insert.y+13},{x:insert.x+11,y:insert.y+13}],insert.color,power,2)}
function drawFlipper(f,color){const ex=f.x+Math.cos(f.angle)*f.length,ey=f.y+Math.sin(f.angle)*f.length,power=.35+lighting.energy*.55+(f.pressed?.35:0);ctx.save();ctx.lineCap='round';ctx.beginPath();ctx.moveTo(f.x+7,f.y+10);ctx.lineTo(ex+7,ey+10);ctx.strokeStyle='rgba(0,0,0,.78)';ctx.lineWidth=f.width+16;ctx.stroke();ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(ex,ey);const chrome=ctx.createLinearGradient(f.x,f.y-20,f.x,f.y+20);chrome.addColorStop(0,'#f9fdff');chrome.addColorStop(.13,'#8f9dad');chrome.addColorStop(.3,color);chrome.addColorStop(.56,'#17202c');chrome.addColorStop(.85,color);chrome.addColorStop(1,'#fff');ctx.strokeStyle=chrome;ctx.lineWidth=f.width+8;ctx.stroke();ctx.shadowColor=color;ctx.shadowBlur=power*26;ctx.globalAlpha=.4+power*.6;ctx.strokeStyle=color;ctx.lineWidth=f.width-3;ctx.stroke();ctx.shadowBlur=0;ctx.globalAlpha=.75;ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.stroke();ctx.globalAlpha=1;ctx.beginPath();ctx.arc(f.x,f.y,19,0,Math.PI*2);const pivot=ctx.createRadialGradient(f.x-7,f.y-8,2,f.x,f.y,19);pivot.addColorStop(0,'#fff');pivot.addColorStop(.42,'#b8c6d6');pivot.addColorStop(1,'#27303c');ctx.fillStyle=pivot;ctx.fill();ctx.restore()}
function drawBall(ball){ctx.save();ctx.beginPath();ctx.ellipse(ball.x+8,ball.y+11,ball.r*1.1,ball.r*.68,0,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,.62)';ctx.fill();const rg=ctx.createRadialGradient(ball.x-7,ball.y-9,1,ball.x,ball.y,ball.r);rg.addColorStop(0,'#fff');rg.addColorStop(.16,'#eaf9ff');rg.addColorStop(.45,'#8c9cad');rg.addColorStop(.72,'#313b48');rg.addColorStop(.92,'#e0f5ff');rg.addColorStop(1,'#0a0d12');ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fillStyle=rg;ctx.shadowBlur=13;ctx.shadowColor=palette.glass;ctx.fill();ctx.shadowBlur=0;ctx.restore()}

function draw(){const light=lighting.snapshot();ctx.save();if(state.shake>0)ctx.translate((Math.random()-.5)*8,(Math.random()-.5)*8);drawBackground(light);for(const lane of lanes)drawLane(lane);drawLCD(light);
 for(let i=0;i<walls.length;i++){const accent=i===7?palette.cyan:i>=8&&i<=13?palette.amber:i>=14&&i<=21?(i%2?palette.cyan:palette.pink):'';const lit=accent?clamp(light.energy*(i<14?1.3:1)+light.pulse*.25,0,1):0;drawRail(walls[i],accent,lit)}
 for(const insert of inserts)drawInsert(insert,light);for(const q of bumpers)drawBumper(q);for(const target of targets)drawTarget(target);for(const post of posts)drawPost(post);drawFlipper(flippers.left,palette.pink);drawFlipper(flippers.right,palette.cyan);
 const ballState=balls[0];ctx.textAlign='center';ctx.font='800 14px sans-serif';ctx.fillStyle=state.ballSave>0?palette.green:'#50596a';ctx.shadowColor=palette.green;ctx.shadowBlur=state.ballSave>0?12:0;ctx.fillText(state.ballSave>0?`BALL SAVE ${Math.ceil(state.ballSave)}`:'BALL SAVE',400,1150);ctx.shadowBlur=0;ctx.font='900 11px sans-serif';ctx.fillStyle=ballState?.kickbacks.left?palette.green:'#414957';ctx.fillText(ballState?.kickbacks.left?'KICKBACK ◀':'KICKBACK USED',91,1008);ctx.fillStyle=ballState?.kickbacks.right?palette.green:'#414957';ctx.fillText(ballState?.kickbacks.right?'▶ KICKBACK':'KICKBACK USED',709,1008);ctx.font='800 14px sans-serif';ctx.fillStyle=state.frenzy>0?palette.pink:'#697386';ctx.fillText(state.frenzy>0?`BUMPER FRENZY ${Math.ceil(state.frenzy)}`:`500 BANK ${state.bumperBank.size}/3   •   A B C ${state.targetHits.size}/3`,400,680);ctx.fillStyle=light.stage>=2?'#f7fbff':'#687285';ctx.font='900 18px "Courier New"';ctx.shadowColor=palette.cyan;ctx.shadowBlur=light.stage>=2?14:0;ctx.fillText(light.stage>=3?'NEON CIRCUIT: FULL POWER':'NEON CIRCUIT',400,735);ctx.shadowBlur=0;
 for(const ball of balls){if(state.launching&&!ball.launched){ctx.fillStyle=palette.pink;ctx.shadowColor=palette.pink;ctx.shadowBlur=18;ctx.fillRect(742,1025,12,state.plunger*120);ctx.shadowBlur=0}drawBall(ball)}
 for(const p of state.particles){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.shadowColor=p.color;ctx.shadowBlur=8;ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-3,6,6)}ctx.shadowBlur=0;ctx.globalAlpha=1;for(const p of state.pop){ctx.globalAlpha=p.life;ctx.fillStyle='#fff';ctx.font='900 23px "Courier New"';ctx.fillText(p.text,p.x,p.y)}ctx.globalAlpha=1;
 // Glass reflection stays subtle so the ball remains legible.
 const glass=ctx.createLinearGradient(80,0,620,1200);glass.addColorStop(0,'rgba(255,255,255,.10)');glass.addColorStop(.18,'rgba(255,255,255,.018)');glass.addColorStop(.43,'transparent');glass.addColorStop(.78,'rgba(95,220,255,.025)');glass.addColorStop(1,'transparent');ctx.fillStyle=glass;ctx.fillRect(0,0,W,H);ctx.restore()}

function loop(now){const frame=Math.min(.033,(now-last)/1000);last=now;acc+=frame;while(acc>=1/120){if(state.running)step(1/120);acc-=1/120}draw();requestAnimationFrame(loop)}
controls();sync();requestAnimationFrame(loop);

// Stable hooks support deterministic physics tuning; acceptance playtests still use visible controls.
window.PinballTest={state,launch,press,roulette,reset,step,setBall:(x,y,vx=0,vy=0)=>{const b=balls[0];if(b)Object.assign(b,{x,y,vx,vy,launched:true,shotGate:true})},getSnapshot:()=>({score:state.score,balls:state.balls,multiplier:state.multiplier,targets:[...state.targetHits],bumperBank:[...state.bumperBank],lanes:[...state.lanes],lighting:lighting.snapshot(),metrics:{...state.metrics},ball:balls[0]&&{x:balls[0].x,y:balls[0].y,vx:balls[0].vx,vy:balls[0].vy,launched:balls[0].launched,shotGate:balls[0].shotGate}})};
