import{W,H,table,bumpers,posts,targets,lanes,palette}from'./config.js?v=20260827-4';import{clamp,circleHit,segmentHit,rectHit,flipperHit,integrate}from'./physics.js?v=20260827-4';import{Roulette}from'./roulette.js?v=20260827-4';import{AudioFX}from'./audio.js?v=20260827-4';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),ui={score:document.querySelector('#score'),high:document.querySelector('#high-score'),multi:document.querySelector('#multiplier'),balls:document.querySelector('#balls'),lcd:document.querySelector('#lcd'),lcdMain:document.querySelector('#lcd-main'),lcdSub:document.querySelector('#lcd-sub'),msg:document.querySelector('#message'),overlay:document.querySelector('#start-overlay'),start:document.querySelector('#start-button'),left:document.querySelector('#left-control'),right:document.querySelector('#right-control')},audio=new AudioFX();
const safeStorage={get(key){try{return localStorage.getItem(key)}catch{return null}},set(key,value){try{localStorage.setItem(key,value)}catch{}}};
const state={running:false,score:0,high:+safeStorage.get('neonRouletteHigh')||0,balls:3,multiplier:1,targetHits:new Set,lanes:new Set,combo:0,comboTime:0,lastHit:'',ballSave:0,frenzy:0,magnet:0,shake:0,flash:0,plunger:0,launching:false,particles:[],pop:[],time:0};
const walls=[
 [{x:58,y:1030},{x:58,y:135}],[{x:58,y:135},{x:145,y:52}],[{x:145,y:52},{x:575,y:52}],[{x:575,y:52},{x:650,y:126}],
 [{x:650,y:126},{x:650,y:1018}],[{x:650,y:1018},{x:572,y:1090}],[{x:58,y:1030},{x:148,y:1090}],
 [{x:88,y:760},{x:190,y:825}],[{x:190,y:825},{x:124,y:905}],[{x:590,y:760},{x:530,y:825}],[{x:530,y:825},{x:580,y:905}],
 [{x:608,y:210},{x:608,y:1045}],[{x:112,y:640},{x:190,y:700}],[{x:608,y:640},{x:530,y:700}]
];
const flippers={left:{x:198,y:1058,length:132,width:27,rest:.34,active:-.55,angle:.34,angularVelocity:0,pressed:false,side:-1},right:{x:522,y:1058,length:132,width:27,rest:Math.PI-.34,active:Math.PI+.55,angle:Math.PI-.34,angularVelocity:0,pressed:false,side:1}};
let balls=[],last=performance.now(),acc=0;
const roulette=new Roulette(awardReward,r=>{ui.lcdMain.textContent=r.label;ui.lcdMain.style.color=r.color;audio.tick()});
function newBall(){balls=[{x:629,y:1010,vx:0,vy:0,r:table.ballRadius,trail:[],launched:false,shotGate:false,saveUsed:false,stuck:0,lastX:0,lastY:0}];state.plunger=0;state.launching=false;ui.lcdMain.textContent='HOLD TO LAUNCH';ui.lcdSub.textContent='右下を押して離す';inputLog('ball-ready',{ballsRemaining:state.balls})}
function reset(){state.score=0;state.balls=3;state.multiplier=1;state.targetHits.clear();state.lanes.clear();state.combo=0;state.ballSave=8;state.frenzy=0;state.magnet=0;state.running=true;state.pop=[];newBall();sync();}
function sync(){ui.score.textContent=Math.floor(state.score).toString().padStart(7,'0');state.high=Math.max(state.high,state.score);ui.high.textContent=Math.floor(state.high).toString().padStart(7,'0');ui.multi.textContent=`×${state.multiplier}`;ui.balls.textContent=Array(Math.max(0,state.balls)).fill('●').join(' ');}
function addScore(v,label,x=360,y=500){const n=v*state.multiplier;state.score+=n;state.pop.push({x,y,text:`+${n}`,life:1});if(label)message(label);sync()}
function message(t){ui.msg.textContent=t;ui.msg.classList.remove('show');void ui.msg.offsetWidth;ui.msg.classList.add('show')}
function inputLog(type,data={}){console.info('[pinball-input]',type,JSON.stringify({at:Math.round(performance.now()),...data}))}
function particles(x,y,color,n=10){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=50+Math.random()*240;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:.4+Math.random()*.5})}}
function registerHit(kind,id,x,y,base){if(state.lastHit!==kind+id&&state.comboTime>0)state.combo++;else if(state.comboTime<=0)state.combo=1;state.lastHit=kind+id;state.comboTime=2.7;addScore(base+Math.max(0,state.combo-1)*100,state.combo>=4?`${state.combo} HIT COMBO!`:null,x,y);if(state.combo===6){state.multiplier=Math.min(5,state.multiplier+1);message(`COMBO ×${state.multiplier}`)} }
function triggerRoulette(){if(roulette.spin()){ui.lcd.classList.add('spin');ui.lcdSub.textContent='CHANCE!';message('ROULETTE!');state.targetHits.clear()}}
function awardReward(r){ui.lcd.classList.remove('spin');ui.lcdMain.textContent=r.label;ui.lcdMain.style.color=r.color;ui.lcdSub.textContent='TARGETS TO RE-SPIN';audio.award();message(r.label);switch(r.id){case'JACKPOT':addScore(25000);break;case'MULTI':state.multiplier=Math.min(5,state.multiplier+1);break;case'FRENZY':state.frenzy=16;break;case'SAVE':state.ballSave=Math.max(state.ballSave,20);break;case'BONUS':state.balls=Math.min(5,state.balls+1);break;case'MAGNET':state.magnet=14;break}sync()}
function press(which,on){const f=flippers[which];if(on&&!f.pressed){audio.flip();navigator.vibrate?.(12)}f.pressed=on;ui[which].classList.toggle('active',on);if(which==='right'&&balls[0]&&!balls[0].launched){if(on){state.launching=true;inputLog('plunger-down',{charge:+state.plunger.toFixed(3)})}else if(state.launching)launch()}}
function launch(){const b=balls[0];if(!b||b.launched)return;const charge=state.plunger,speed=1580+charge*470;b.launched=true;b.vy=-speed;b.vx=0;state.launching=false;state.ballSave=b.saveUsed?0:8;inputLog('launch',{charge:+charge.toFixed(3),speed:Math.round(speed),saveAvailable:!b.saveUsed,x:b.x,y:b.y});audio.tone(90,.16,'sawtooth',.08,260);ui.lcdMain.textContent='BALL IN PLAY';ui.lcdSub.textContent='3 TARGETS → SPIN'}
function controls(){const activePointers=new Map,releasePointer=id=>{const name=activePointers.get(id);if(!name)return;activePointers.delete(id);if(![...activePointers.values()].includes(name))press(name,false);inputLog('pointer-up',{id,name})},releaseAll=()=>{for(const id of[...activePointers.keys()])releasePointer(id)},bind=(name,el)=>{el.addEventListener('pointerdown',e=>{e.preventDefault();if(activePointers.has(e.pointerId))return;activePointers.set(e.pointerId,name);press(name,true);inputLog('pointer-down',{id:e.pointerId,name,type:e.pointerType});try{el.setPointerCapture?.(e.pointerId)}catch(err){inputLog('capture-unavailable',{name,error:err?.name||'unknown'})}});el.addEventListener('pointerup',e=>releasePointer(e.pointerId));el.addEventListener('pointercancel',e=>releasePointer(e.pointerId));el.addEventListener('lostpointercapture',e=>releasePointer(e.pointerId));if(!window.PointerEvent){el.addEventListener('touchstart',e=>{e.preventDefault();for(const t of e.changedTouches){const id=`touch-${t.identifier}`;activePointers.set(id,name);press(name,true);inputLog('touch-down',{id,name})}},{passive:false});for(const type of['touchend','touchcancel'])el.addEventListener(type,e=>{e.preventDefault();for(const t of e.changedTouches)releasePointer(`touch-${t.identifier}`)},{passive:false})}};bind('left',ui.left);bind('right',ui.right);addEventListener('pointerup',e=>releasePointer(e.pointerId));addEventListener('pointercancel',e=>releasePointer(e.pointerId));addEventListener('blur',releaseAll);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseAll()});addEventListener('keydown',e=>{if(['ArrowLeft','KeyZ'].includes(e.code))press('left',true);if(['ArrowRight','KeyX','Space'].includes(e.code))press('right',true)});addEventListener('keyup',e=>{if(['ArrowLeft','KeyZ'].includes(e.code))press('left',false);if(['ArrowRight','KeyX','Space'].includes(e.code))press('right',false)});ui.start.onclick=()=>{ui.overlay.classList.add('hidden');ui.overlay.inert=true;ui.start.disabled=true;reset();inputLog('game-start');try{audio.init()}catch(err){inputLog('audio-unavailable',{error:err?.name||'unknown'})}};canvas.addEventListener('pointerdown',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height;if(y<=820)return;const name=x<canvas.width/2?'left':'right';activePointers.set(e.pointerId,name);press(name,true);inputLog('canvas-down',{id:e.pointerId,name,type:e.pointerType,x:Math.round(x),y:Math.round(y)});try{canvas.setPointerCapture?.(e.pointerId)}catch(err){inputLog('capture-unavailable',{name,error:err?.name||'unknown'})}});canvas.addEventListener('pointerup',e=>releasePointer(e.pointerId));canvas.addEventListener('pointercancel',e=>releasePointer(e.pointerId));}
function updateFlipper(f,dt){const target=f.pressed?f.active:f.rest,d=target-f.angle,vel=clamp(d*42,-24,24);f.angularVelocity=vel;f.angle+=vel*dt;if(Math.abs(d)<.012){f.angle=target;f.angularVelocity=0}}
function step(dt){state.time+=dt;roulette.update(dt);updateFlipper(flippers.left,dt);updateFlipper(flippers.right,dt);if(state.launching)state.plunger=clamp(state.plunger+dt*.75,0,1);if(state.comboTime>0){state.comboTime-=dt;if(state.comboTime<=0)state.combo=0}state.ballSave=Math.max(0,state.ballSave-dt);state.frenzy=Math.max(0,state.frenzy-dt);state.magnet=Math.max(0,state.magnet-dt);state.shake=Math.max(0,state.shake-dt);state.flash=Math.max(0,state.flash-dt);
 for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=300*dt;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);for(const p of state.pop){p.y-=40*dt;p.life-=dt}state.pop=state.pop.filter(p=>p.life>0);
 for(const b of balls){if(!b.launched)continue;b.lastX=b.x;b.lastY=b.y;integrate(b,dt);if(!b.shotGate&&b.x>606&&b.y<225&&b.vy<0){b.x=570;b.y=210;b.vx=-680;b.vy=Math.min(-620,b.vy*.72);b.shotGate=true;inputLog('shooter-exit',{x:b.x,y:b.y,vx:Math.round(b.vx),vy:Math.round(b.vy)});particles(608,205,palette.cyan,12);message('SKILL SHOT!')}if(b.shotGate&&b.x>607&&b.y>865){b.x=586;b.vx=-Math.max(420,Math.abs(b.vx));}if(state.magnet>0&&b.y<650){const dx=360-b.x,dy=365-b.y,d=Math.hypot(dx,dy);if(d<310){b.vx+=dx/d*190*dt;b.vy+=dy/d*190*dt}}
  for(let k=0;k<2;k++){for(const [a,z]of walls)segmentHit(b,a,z,.64);for(const p of posts)if(circleHit(b,p.x,p.y,p.r,.78,20))particles(p.x,p.y,palette.cyan,3);for(const [side,f]of Object.entries(flippers)){if(flipperHit(b,f)&&!f.hitCool){f.hitCool=.12;inputLog('flipper-hit',{side,pressed:f.pressed,x:Math.round(b.x),y:Math.round(b.y),vx:Math.round(b.vx),vy:Math.round(b.vy)})}}}for(const f of Object.values(flippers))f.hitCool=Math.max(0,(f.hitCool||0)-dt);
  for(let i=0;i<bumpers.length;i++){const q=bumpers[i];if(circleHit(b,q.x,q.y,q.r,.82,state.frenzy>0?520:380)){if(!q.cool){q.cool=.09;registerHit('bumper',i,q.x,q.y,state.frenzy>0?q.score*3:q.score);audio.bumper();particles(q.x,q.y,q.color,14);state.shake=.12;navigator.vibrate?.(8)}}q.cool=Math.max(0,(q.cool||0)-dt)}
  for(const t of targets){if(rectHit(b,t)&&!t.cool){t.cool=.38;b.vy-=320;b.vx+=Math.sin(t.angle)*260;state.targetHits.add(t.id);registerHit('target',t.id,t.x,t.y,1000);audio.target();particles(t.x,t.y,t.color,12);if(state.targetHits.size===3)triggerRoulette()}t.cool=Math.max(0,(t.cool||0)-dt)}
  if(b.lastY>170&&b.y<=170){for(const l of lanes)if(Math.abs(b.x-l.x)<54&&!state.lanes.has(l.id)){state.lanes.add(l.id);registerHit('lane',l.id,l.x,155,1250);particles(l.x,150,palette.amber,8);if(state.lanes.size===3){state.lanes.clear();state.multiplier=Math.min(5,state.multiplier+1);addScore(5000,`LANES ×${state.multiplier}`)}}}
  const move=Math.hypot(b.x-b.lastX,b.y-b.lastY);b.stuck=move<.05?b.stuck+dt:0;if(b.stuck>2.2&&b.y<1050){b.vx+=(Math.random()-.5)*300;b.vy-=230;b.stuck=0;message('BALL SEARCH')}
  if(b.y>table.drainY)drain(b);
 }
}
function drain(b){if(!balls.includes(b))return;if(state.ballSave>0&&!b.saveUsed){Object.assign(b,{x:629,y:1010,vx:0,vy:0,launched:false,shotGate:false,saveUsed:true,stuck:0,lastX:629,lastY:1010});state.launching=false;state.plunger=0;state.ballSave=0;ui.lcdMain.textContent='BALL SAVED';ui.lcdSub.textContent='右下を押して再発射';message('BALL SAVED!');inputLog('ball-saved-ready');audio.award();return}balls.splice(balls.indexOf(b),1);state.balls--;inputLog('drain',{ballsRemaining:state.balls});audio.drain();sync();if(state.balls>0){message('SHOOT AGAIN');setTimeout(()=>state.running&&newBall(),850)}else gameOver()}
function gameOver(){state.running=false;safeStorage.set('neonRouletteHigh',Math.floor(state.high));ui.overlay.inert=false;ui.start.disabled=false;ui.overlay.classList.remove('hidden');ui.start.textContent='PLAY AGAIN';ui.overlay.querySelector('p').innerHTML=`GAME OVER<br><strong>${Math.floor(state.score).toLocaleString()} pts</strong>`;ui.lcdMain.textContent='GAME OVER';inputLog('game-over',{score:Math.floor(state.score)})}
function drawPath(points,color,width=5){ctx.save();ctx.beginPath();ctx.moveTo(points[0].x+5,points[0].y+8);for(const p of points.slice(1))ctx.lineTo(p.x+5,p.y+8);ctx.strokeStyle='rgba(0,0,0,.72)';ctx.lineWidth=width+12;ctx.stroke();ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.strokeStyle='#343b4c';ctx.lineWidth=width+10;ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=width+4;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=Math.max(2,width*.28);ctx.stroke();ctx.restore()}
function draw(){ctx.save();if(state.shake>0)ctx.translate((Math.random()-.5)*8,(Math.random()-.5)*8);const g=ctx.createRadialGradient(360,180,40,360,650,760);g.addColorStop(0,'#313960');g.addColorStop(.28,'#142343');g.addColorStop(.72,'#120f26');g.addColorStop(1,'#050710');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const edge=ctx.createLinearGradient(0,0,W,0);edge.addColorStop(0,'rgba(0,0,0,.72)');edge.addColorStop(.12,'transparent');edge.addColorStop(.88,'transparent');edge.addColorStop(1,'rgba(0,0,0,.8)');ctx.fillStyle=edge;ctx.fillRect(0,0,W,H);
 ctx.globalAlpha=.16;ctx.strokeStyle='#46f5ff';ctx.lineWidth=2;for(let y=0;y<H;y+=46){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y+160);ctx.stroke()}ctx.globalAlpha=1;
 // top lanes and orbit markings
 for(const l of lanes){ctx.fillStyle=state.lanes.has(l.id)?palette.amber:'#202742';ctx.fillRect(l.x-43,88,86,88);ctx.strokeStyle=state.lanes.has(l.id)?'#fff':'#536083';ctx.lineWidth=4;ctx.strokeRect(l.x-43,88,86,88);ctx.fillStyle='#fff';ctx.font='bold 24px monospace';ctx.textAlign='center';ctx.fillText(l.id,l.x,143)}
 ctx.fillStyle='#05050b';ctx.fillRect(222,430,276,132);ctx.strokeStyle=palette.pink;ctx.shadowBlur=18;ctx.shadowColor=palette.pink;ctx.lineWidth=7;ctx.strokeRect(222,430,276,132);ctx.shadowBlur=0;
 for(const [a,b]of walls)drawPath([a,b],palette.rail,7);drawPath([{x:608,y:210},{x:608,y:1045}],palette.cyan,3);
 for(const q of bumpers){ctx.beginPath();ctx.ellipse(q.x+7,q.y+13,q.r+12,q.r*.92,0,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,.65)';ctx.fill();const bg=ctx.createRadialGradient(q.x-16,q.y-20,4,q.x,q.y,q.r+10);bg.addColorStop(0,'#fff');bg.addColorStop(.18,q.color);bg.addColorStop(.62,'#272b3c');bg.addColorStop(1,'#080a12');ctx.beginPath();ctx.arc(q.x,q.y,q.r+9,0,Math.PI*2);ctx.fillStyle=bg;ctx.fill();ctx.strokeStyle=q.color;ctx.shadowBlur=q.cool?32:15;ctx.shadowColor=q.color;ctx.lineWidth=q.cool?10:6;ctx.stroke();ctx.shadowBlur=0;ctx.beginPath();ctx.ellipse(q.x,q.y-7,q.r-16,(q.r-16)*.72,0,0,Math.PI*2);ctx.fillStyle=q.cool?'#fff':q.color;ctx.globalAlpha=.88;ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#10101a';ctx.font='900 22px monospace';ctx.fillText('500',q.x,q.y)}
 for(const t of targets){ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.angle);ctx.fillStyle='#090b12';ctx.fillRect(-t.w/2+6,-t.h/2+9,t.w,t.h);const tg=ctx.createLinearGradient(0,-t.h/2,0,t.h/2);tg.addColorStop(0,'#fff');tg.addColorStop(.22,state.targetHits.has(t.id)?'#fff':t.color);tg.addColorStop(1,'#521535');ctx.fillStyle=tg;ctx.shadowColor=t.color;ctx.shadowBlur=16;ctx.fillRect(-t.w/2,-t.h/2,t.w,t.h);ctx.shadowBlur=0;ctx.fillStyle='#10121a';ctx.font='900 16px sans-serif';ctx.fillText(t.id,0,6);ctx.restore()}
 for(const p of posts){ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='#dce6f4';ctx.fill();ctx.strokeStyle='#4f5a70';ctx.lineWidth=5;ctx.stroke()}
 drawFlipper(flippers.left,palette.pink);drawFlipper(flippers.right,palette.cyan);
 // inserts, arrows, ball saver indicator
 ctx.font='700 16px sans-serif';ctx.fillStyle=state.ballSave>0?'#8aff80':'#4b5062';ctx.textAlign='center';ctx.fillText(state.ballSave>0?`BALL SAVE ${Math.ceil(state.ballSave)}`:'BALL SAVE',360,1142);ctx.fillStyle=state.frenzy>0?palette.pink:'#60667b';ctx.fillText(state.frenzy>0?`BUMPER FRENZY ${Math.ceil(state.frenzy)}`:'A   B   C → ROULETTE',360,625);
 for(const b of balls){if(state.launching&&!b.launched){ctx.fillStyle='#ff3da9';ctx.fillRect(623,1025,12,state.plunger*120)}ctx.beginPath();ctx.ellipse(b.x+7,b.y+10,b.r*1.05,b.r*.62,0,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,.58)';ctx.fill();const rg=ctx.createRadialGradient(b.x-6,b.y-8,1,b.x,b.y,b.r);rg.addColorStop(0,'#fff');rg.addColorStop(.22,'#eef6ff');rg.addColorStop(.52,'#8b98a8');rg.addColorStop(.82,'#303846');rg.addColorStop(1,'#0b0e14');ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=rg;ctx.shadowBlur=11;ctx.shadowColor='#bceeff';ctx.fill();ctx.shadowBlur=0}
 for(const p of state.particles){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-3,6,6)}ctx.globalAlpha=1;for(const p of state.pop){ctx.globalAlpha=p.life;ctx.fillStyle='#fff';ctx.font='900 23px monospace';ctx.fillText(p.text,p.x,p.y)}ctx.restore()}
function drawFlipper(f,color){const ex=f.x+Math.cos(f.angle)*f.length,ey=f.y+Math.sin(f.angle)*f.length;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(f.x+6,f.y+10);ctx.lineTo(ex+6,ey+10);ctx.strokeStyle='rgba(0,0,0,.72)';ctx.lineWidth=f.width+14;ctx.stroke();ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(ex,ey);ctx.strokeStyle='#202433';ctx.lineWidth=f.width+10;ctx.stroke();const fg=ctx.createLinearGradient(f.x,f.y-18,f.x,f.y+18);fg.addColorStop(0,'#fff');fg.addColorStop(.18,color);fg.addColorStop(1,'#481535');ctx.strokeStyle=fg;ctx.shadowBlur=17;ctx.shadowColor=color;ctx.lineWidth=f.width;ctx.stroke();ctx.shadowBlur=0;ctx.lineCap='butt';ctx.beginPath();ctx.arc(f.x,f.y,18,0,Math.PI*2);const pg=ctx.createRadialGradient(f.x-6,f.y-7,2,f.x,f.y,18);pg.addColorStop(0,'#fff');pg.addColorStop(.45,'#b8c4d6');pg.addColorStop(1,'#343b49');ctx.fillStyle=pg;ctx.fill()}
function loop(now){let frame=Math.min(.033,(now-last)/1000);last=now;acc+=frame;while(acc>=1/120){if(state.running)step(1/120);acc-=1/120}draw();requestAnimationFrame(loop)}controls();sync();requestAnimationFrame(loop);
// Stable hooks for automated tuning and regression playtests.
window.PinballTest={state,launch,press,roulette,reset,step,setBall:(x,y,vx=0,vy=0)=>{const b=balls[0];if(b)Object.assign(b,{x,y,vx,vy,launched:true,shotGate:true})},getSnapshot:()=>({score:state.score,balls:state.balls,multiplier:state.multiplier,targets:[...state.targetHits],lanes:[...state.lanes],ball:balls[0]&&{x:balls[0].x,y:balls[0].y,vx:balls[0].vx,vy:balls[0].vy,launched:balls[0].launched,shotGate:balls[0].shotGate}})};
